
name: T. K. Daisy Leung, Astronomer
author: T. K. Daisy Leung
description: Astronomer
email: leungtszkuk@gmail.com
markdown: kramdown
markdown_ext: "md, markdown"
permalink: /blog/:year/:month/:day/:title

# generate site.travel
collections:
  travel:
    name: Travel
    url: /travel/
    output: true
    permalink: /travel/year/:month/:day/:title/

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "astro313"

# Social media
twitter_username: tkdaisyleung
github_username: astro313
linkedin_username: tsz-kuk-daisy-leung-4a5415151

# Google Analytics
google_analytics: UA-128279314-1

future: true

keywords:
  - travel blog
  - photo blog
  - tourist photos
  - landscape photos
  - travel in US
  - Canada photos
  - interesting places
  - travel tips
  - projects
  - flickr
  - photography
  - PhD
  - Academia
  - work-life balance
